name: machine_learning
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - pillow
  - scikit-image
  - scikit-learn
  - torchvision
  - pip:
    - opencv-python==4.1.0.25
    - scipy==1.1.0
